Name: Senden
Description: Token versenden
Tasks:
  - Name: Balance check
    Command:
      - tezos-client get balance for Wallet1
    Register: balance1

  - Name: Send tezos
    Command:
      - tezos-client transfer 100 from Wallet1 to Wallet2
    Blocking: false

  - Name: "Bake"
    WaitBlocks: 1

  - Name: Balance check
    Command:
      - tezos-client get balance for Wallet1
